### ISSUE TITLE
ImportError: cannot import name 'Config' from 'pytimeloop'

### ISSUE THREAD

**Issue by chenshih1** [Accelergy-Project/timeloop-python#28]
Hello, I've installed the package following the instructions, but I failed to get the correct output while testing `timeloop-model.py --help`.

`root@6cd30001db42:~/accelergy-timeloop-infrastructure/src/timeloop-python# timeloop-model.py --help
Traceback (most recent call last):
  File "/root/.local/bin/timeloop-model.py", line 4, in <module>
    from pytimeloop import Config
ImportError: cannot import name 'Config' from 'pytimeloop' (/root/.local/lib/python3.8/site-packages/pytimeloop/__init__.py)`

How can I fix this problem?

**Comment by halfmanli** [comment]
I meet the same error

**Comment by gilbertmike** [comment]
The C++ bindings and Python code fell out of sync. I've fixed this.
