### ISSUE TITLE
Why should we map loop to defferent memory level?

### ISSUE THREAD

**Issue by loveHoloForeever** [Accelergy-Project/timeloop-python#3]
I have read your paper and thought it was wonderful, but I still have a few questions. What is the operation of mapping a loop to a memory level? How to execute it? What kind of benefits can this bring?

**Comment by nellie-wu** [comment]
Mapping different loops to different storage units allow us to model how much data is stored in each storage for reuse. Please check out the timeloop-accelergy tutorial: https://accelergy.mit.edu/tutorial.html for more details.
