### ISSUE TITLE
Binding Issue

### ISSUE THREAD

**Issue by felix0901** [Accelergy-Project/timeloop-python#7]
Hi,

Thanks for the nice work.
I followed the installation instruction and installed it successfully. However, when I run it, it shows this error. Do you have any suggestions on how could I solve this?

`File "Documents/my_code/public/new_timeloop_python/timeloop-python/pytimeloop/__init__.py", line 1, in <module>
    from bindings import *
ImportError: Documents/my_code/public/new_timeloop_python/timeloop-python/bindings.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN6search12HybridSearchE`

**Comment by gilbertmike** [comment]
@felix0901 Sorry for the late response. Is this still an issue?

**Comment by gilbertmike** [comment]
Did you confirm if it was a bug within PyTimeloop or an issue in your build environment?

**Comment by felix0901** [comment]
It was my build environment.
